config/routes.rb
Rails.application.routes.draw do
  resources :dealeravatars
  resources :dealerphotos
  resources :singles
  resources :boxes
  resources :demonstration_attachments
  resources :meet_sr_farmers
  resources :meet_fas
  resources :meet_dealers
  resources :meet_state_managers
  resources :business_developments
  resources :sr_activities
  resources :post_demonstrations
  get 'demo_date/populate_dates'

  resources :demonstrations
  resources :farmers
  resources :dealer_blanks
  resources :blank_checks
  resources :dealer_securities
  resources :security_checks
  resources :dealer_props
  resources :proprietors
  resources :positions
  resources :fa_targets
  resources :targets
  resources :field_assistants
  resources :pocket_crops
  resources :pocket_districts
  resources :pocket_dats
  resources :pocket_infos
  resources :villages
  resources :talukas
  resources :crops
  resources :districts
  resources :pockets
  resources :products
  resources :applications
  resources :pre_demonstrations
  resources :assist_reps
  resources :dealer_visits
  resources :product_prescriptions
  resources :meet_farmers
  resources :fa_activities
  resources :banks
  resources :dealers
  resources :demos
  resources :pockets
  resources :demoresults
  resources :prodsamples
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'home#index'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated
    end
  end
  resources :users
  resources :states

  resources :home

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @demos = Demonstration.where(demo_status: 'active')
    @dealers = Dealer.where(call: false)
    @prodsample =Prodsample.all
    @fieldassistants = Position.where(form:nil )
    @farmers = Farmer.where(callverified: nil)
    @positions = Position.all

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!-- /Page header -->

<!-- Timeline -->
<div class="timeline">

  <!-- Line component -->
  <div class="line text-muted"></div>


  <!-- Panel -->
  <article class="panel panel-primary">

    <!-- Icon -->
    <div class="panel-heading icon">
      <i class="glyphicon glyphicon-chevron-right"></i>
    </div>
    <!-- /Icon -->

    <!-- Heading -->
    <div class="panel-heading">
      <h1 class="panel-title"><b>Actions</b></h1>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-3">
         <%= link_to 'Register New Dealer', new_dealer_path, class: "btn btn-block btn-success btn-lg btn3d",:style => "color: #FFFFFF" %>
        </div>
        <div class="col-md-3">
          <%= link_to 'Register New Farmer', new_farmer_path, class: "btn btn-block btn-success btn-lg btn3d",:style => "color: #FFFFFF" %>
        </div>
        <div class="col-md-3">
          <%= link_to 'Register Field Assistant', new_field_assistant_path, class: 'btn btn-block btn-success btn-lg btn3d',:style => "color: #FFFFFF" %>
        </div>
        <div class="col-md-3">
          <%= link_to "Register New Pocket", new_pocket_path, class: 'btn btn-block btn-success btn-lg btn3d',:style => "color: #FFFFFF" %>
        </div>
      </div>

    </div>
    <!-- /Body -->

    <!-- Footer -->
    <div class="panel-footer">
      <div class="row">
        <div class="col-md-3">
          <%= link_to "Request Product Sample", new_prodsample_path, class: 'btn btn-block btn-primary btn-lg btn3d',:style => "color: #FFFFFF" %>
        </div>
        <div class="col-md-3">
          <%= link_to 'Upload Product Results', new_demoresult_path, class: "btn btn-block btn-primary btn-lg btn3d",:style => "color: #FFFFFF" %>
        </div>
        <div class="col-md-3">
          <%= link_to 'Field Assistant Activities', new_fa_activity_path, class: 'btn btn-block btn-primary btn-lg btn3d',:style => "color: #FFFFFF" %>
        </div>
        <div class="col-md-3">
          <%= link_to "Sales Rep Activities", new_sr_activity_path, class: 'btn btn-block btn-primary btn-lg btn3d',:style => "color: #FFFFFF" %>
        </div>
      </div>
      <br>
    </div>
    <!-- /Footer -->

  </article>
  <!-- /Panel -->

  <!-- Separator -->

  <!-- /Separator -->

  <!-- Panel -->
  <article class="panel panel-success">

    <!-- Icon -->
    <div class="panel-heading icon">
      <i class="glyphicon glyphicon-folder-open"></i>
    </div>
    <!-- /Icon -->

    <!-- Heading -->
    <div class="panel-heading">
      <h1 class="panel-title"><b>Open Actions</b></h1>
    </div>
    <!-- /Heading -->

    <!-- Body -->

    <!-- /Body -->

    <!-- List group -->
    <ul class="list-group">
      <div class="row">
        <div class="col-md-6">
      <li class="list-group-item"> <label class="text-left">
        Dealer Registration Form
      </label>
        <%=link_to @dealers.count, dealers_path(:active=>'checkem') %></li>
      <li class="list-group-item"> <label class="text-left">
        Farmer Registration Form
      </label>
        <%=link_to @farmers.count, farmers_path(:active=>'checkem') %></li>
      <li class="list-group-item"> <label class="text-left">
        Activity Demo
      </label>
        <%=link_to @demos.count, demonstrations_path(:active=>'checkem') %></li>
          </div>
        <div class="col-md-6">
      <li class="list-group-item"> <label class="text-left">
        Product Sample Order
      </label>
        <%=link_to @prodsample.count, prodsamples_path %></li>
      <li class="list-group-item"> <label class="text-left">
        Field Assistant Registration
      </label>
        <%=link_to @fieldassistants.count, positions_path(:active=>'checkem') %></li>
      <li class="list-group-item"> <label class="text-left">
        Field Assistant Activity
      </label>
        <%=link_to "0", root_path %></li>
          </div>
        </div>
    </ul>

  </article>
  <!-- /Panel -->

  <!-- Panel -->
  <article class="panel panel-info panel-outline">

    <!-- /Body -->

  </article>
  <!-- /Panel -->

</div>
<!-- /Timeline -->