config/routes.rb
Rails.application.routes.draw do
  resources :dealeravatars
  resources :dealerphotos
  resources :singles
  resources :boxes
  resources :demonstration_attachments
  resources :meet_sr_farmers
  resources :meet_fas
  resources :meet_dealers
  resources :meet_state_managers
  resources :business_developments
  resources :sr_activities
  resources :post_demonstrations
  get 'demo_date/populate_dates'

  resources :demonstrations
  resources :farmers
  resources :dealer_blanks
  resources :blank_checks
  resources :dealer_securities
  resources :security_checks
  resources :dealer_props
  resources :proprietors
  resources :positions
  resources :fa_targets
  resources :targets
  resources :field_assistants
  resources :pocket_crops
  resources :pocket_districts
  resources :pocket_dats
  resources :pocket_infos
  resources :villages
  resources :talukas
  resources :crops
  resources :districts
  resources :pockets
  resources :products
  resources :applications
  resources :pre_demonstrations
  resources :assist_reps
  resources :dealer_visits
  resources :product_prescriptions
  resources :meet_farmers
  resources :fa_activities
  resources :banks
  resources :dealers
  resources :demos
  resources :pockets
  resources :demoresults
  resources :prodsamples
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'home#index'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated
    end
  end
  resources :users
  resources :states

  resources :home

end

app/models/crop.rb
class Crop < ActiveRecord::Base
has_many :pockets
has_many :fa_targets
has_many :pre_demonstrations
has_many :farmers
has_many :farmcrops

has_many :pockets, through: :pocket_crops
has_many :pocket_crops
has_many :meet_sr_farmers
has_many :product_prescriptions

end

app/controllers/crops_controller.rb
class CropsController < ApplicationController
  before_action :set_crop, only: [:show, :edit, :update, :destroy]

  # GET /crops
  # GET /crops.json
  def index
    @crops = Crop.paginate(page: params[:page], per_page: 20)
  end

  # GET /crops/1
  # GET /crops/1.json
  def show
  end

  # GET /crops/new
  def new
    @crop = Crop.new
  end

  # GET /crops/1/edit
  def edit
  end

  # POST /crops
  # POST /crops.json
  def create
    @crop = Crop.new(crop_params)

    respond_to do |format|
      if @crop.save
        format.html { redirect_to @crop, notice: 'Crop was successfully created.' }
        format.json { render :show, status: :created, location: @crop }
      else
        format.html { render :new }
        format.json { render json: @crop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crops/1
  # PATCH/PUT /crops/1.json
  def update
    respond_to do |format|
      if @crop.update(crop_params)
        format.html { redirect_to @crop, notice: 'Crop was successfully updated.' }
        format.json { render :show, status: :ok, location: @crop }
      else
        format.html { render :edit }
        format.json { render json: @crop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crops/1
  # DELETE /crops/1.json
  def destroy
    @crop.destroy
    respond_to do |format|
      format.html { redirect_to crops_url, notice: 'Crop was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crop
      @crop = Crop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crop_params
      params.require(:crop).permit(:crop)
    end
end

app/helpers/crops_helper.rb
module CropsHelper
end

app/views/crops/_form.html.erb
<%= form_for(@crop) do |f| %>
  <% if @crop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crop.errors.count, "error") %> prohibited this crop from being saved:</h2>

      <ul>
      <% @crop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-4">

  </div>
  <div class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h1 class="panel-title text-center">
          <%= link_to 'Back', crops_path, class: "btn btn-success pull-left",:style=>'color:#FFFFFF' %>
          <%= link_to 'Cancel', root_path, class: "btn btn-danger pull-right",:style=>'color:#FFFFFF' %>
          <b>New Crop</b>
        </h1>
      </div>
      <div class="panel-body">
        <div class="field">
          <%= f.label :crop, "Crop Name" %><br>
          <%= f.text_field :crop,{class: "form-control"} %>
        </div>
        <div class="actions">
          <%= f.submit "Submit", class: "btn btn-primary pull-right"%>
        </div>
<% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4">

  </div>
</div>

app/views/crops/edit.html.erb
<h1>Editing Crop</h1>

<%= render 'form' %>

<%= link_to 'Show', @crop %> |
<%= link_to 'Back', crops_path %>

app/views/crops/index.html.erb
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>
  </title>
  <link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"
        rel="stylesheet">
</head>

<body>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      </div>
    <div class="col-md-4">
  <div class="panel panel-default">
    <div class="panel-heading ">
      <h1 class="panel-title ">
        <%= link_to 'New Crop', new_crop_path, 'data-no-turbolink' => true, class: "btn btn-success pull-right",:style=>'color:#FFFFFF'%>
        <b> Crops</b>
      </h1>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-12">
          <table class="table table-bordered">
            <tbody>
            <tr>
            </tr>
            <tr>
              <% @crops.each do |crop| %>
                  <td class="text-center">
                    <%= crop.crop %>
                  </td>
                  <td class="text-center">
                  <%= link_to 'Edit', edit_crop_path(crop),class: "btn btn-info",:style=>'color:#FFFFFF' %>
                  <%= link_to 'Delete', crop, class: "btn btn-danger",:style=>'color:#FFFFFF', method: :delete, data: { confirm: 'Are you sure?' } %>
                  </td>
                  </tr>
              <% end %>
              </tbody>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
        </div>
      </div>
    </div>
  </div>
      </div>
    <div class="col-md-4">
      </div>
    </div>
  </div>
</div>
</body>

app/views/crops/new.html.erb
<%= render 'form' %>

app/views/crops/show.html.erb
<div class="row">
  <div class="col-md-4">

  </div>
  <div class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h1 class="panel-title text-center">
          <%= link_to 'Back', crops_path, class: "btn btn-success pull-left",:style=>'color:#FFFFFF'%>
          <%= link_to 'Edit', edit_crop_path(@crop), class: "btn btn-info pull-left",:style=>'color:#FFFFFF' %>
          <%= link_to 'Delete', crop_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger pull-right", :style=> 'color:#FFFFFF' %>
          <b><%= @crop.crop %></b>
        </h1>
      </div>
      <div class="panel-body">
        <p>
          <strong>Crop:</strong>
          <%= @crop.crop %>
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-4">

  </div>
</div>