config/routes.rb
Rails.application.routes.draw do
  resources :dealeravatars
  resources :dealerphotos
  resources :singles
  resources :boxes
  resources :demonstration_attachments
  resources :meet_sr_farmers
  resources :meet_fas
  resources :meet_dealers
  resources :meet_state_managers
  resources :business_developments
  resources :sr_activities
  resources :post_demonstrations
  get 'demo_date/populate_dates'

  resources :demonstrations
  resources :farmers
  resources :dealer_blanks
  resources :blank_checks
  resources :dealer_securities
  resources :security_checks
  resources :dealer_props
  resources :proprietors
  resources :positions
  resources :fa_targets
  resources :targets
  resources :field_assistants
  resources :pocket_crops
  resources :pocket_districts
  resources :pocket_dats
  resources :pocket_infos
  resources :villages
  resources :talukas
  resources :crops
  resources :districts
  resources :pockets
  resources :products
  resources :applications
  resources :pre_demonstrations
  resources :assist_reps
  resources :dealer_visits
  resources :product_prescriptions
  resources :meet_farmers
  resources :fa_activities
  resources :banks
  resources :dealers
  resources :demos
  resources :pockets
  resources :demoresults
  resources :prodsamples
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'home#index'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated
    end
  end
  resources :users
  resources :states

  resources :home

end

app/models/box.rb
class Box < ActiveRecord::Base
  has_many :product_boxes
  has_many :products, through:  :product_boxes
  has_many :product_applications
  has_many :prodsamples
end

app/models/pre_demonstration.rb
class PreDemonstration < ActiveRecord::Base
  belongs_to :fa_activity
  has_many :applications
  has_many :demonstrations
  has_many :business_developments
  belongs_to :farmer
  belongs_to :crop
  accepts_nested_attributes_for :applications, allow_destroy: true, reject_if: lambda{|a| a[:app_area].blank?}
  before_create :pre_demo_code_maker

  def pre_demo_code_maker
    state_name = self.fa_activity.state.state
   first_name = self.fa_activity.user.first_name
    sur_name = self.fa_activity.user.sur_name
    crop_name = self.crop.crop

    self.demo_code=state_name+'-'+crop_name+'-'+first_name[0]+sur_name[0]+'-'+self.fa_activity.id.to_s
  end


end

app/controllers/pre_demonstrations_controller.rb
class PreDemonstrationsController < ApplicationController
  before_action :set_pre_demonstration, only: [:show, :edit, :update, :destroy]
  before_action :input_user, only: [:new,:edit, :update,:destroy]

  # GET /pre_demonstrations
  # GET /pre_demonstrations.json
  def index
    if params[:pending]
      @positions=Position.find(params[:pending])
      @pre_demonstrations= @positions.fa_activities.collect(&:pre_demonstrations).flatten.uniq

    else
    @pre_demonstrations = PreDemonstration.all
      end
  end

  # GET /pre_demonstrations/1
  # GET /pre_demonstrations/1.json
  def show
  end

  # GET /pre_demonstrations/new
  def new
    @pre_demonstration = PreDemonstration.new
  end

  # GET /pre_demonstrations/1/edit
  def edit
  end

  # POST /pre_demonstrations
  # POST /pre_demonstrations.json
  def create
    @pre_demonstration = PreDemonstration.new(pre_demonstration_params)

    respond_to do |format|
      if @pre_demonstration.save
        format.html { redirect_to @pre_demonstration, notice: 'Pre demonstration was successfully created.' }
        format.json { render :show, status: :created, location: @pre_demonstration }
      else
        format.html { render :new }
        format.json { render json: @pre_demonstration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pre_demonstrations/1
  # PATCH/PUT /pre_demonstrations/1.json
  def update
    respond_to do |format|
      if @pre_demonstration.update(pre_demonstration_params)
        format.html { redirect_to @pre_demonstration, notice: 'Pre demonstration was successfully updated.' }
        format.json { render :show, status: :ok, location: @pre_demonstration }
      else
        format.html { render :edit }
        format.json { render json: @pre_demonstration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pre_demonstrations/1
  # DELETE /pre_demonstrations/1.json
  def destroy
    @pre_demonstration.destroy
    respond_to do |format|
      format.html { redirect_to pre_demonstrations_url, notice: 'Pre demonstration was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def input_user
    redirect_to root_url, notice: 'Your account does not have access to this resource' unless current_user.access?
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_pre_demonstration
      @pre_demonstration = PreDemonstration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pre_demonstration_params
      params.require(:pre_demonstration).permit(:farmer_id, :crop_id, :fa_activity, :crop_growth, :condition, :status, :demo_code,
                                                applications_attributes: [:id,:pre_demonstration_id,:app_area,:app_date,:competitor,:app_type,:follow_date,{product_ids: []},:_destroy])
    end
end

app/helpers/pre_demonstrations_helper.rb
module PreDemonstrationsHelper
end

app/views/pre_demonstrations/_application_fields.html.erb
<div class="nested-fields">
<div class="field">
  <%= f.label :pre_demonstration_id %><br>
  <%= f.number_field :pre_demonstration_id,{class:"form-control", :style => "width:200px"} %>
</div>
<div class="field">
  <%= f.label :app_area, 'Area of application' %><br>
  <%= f.text_field :app_area,{class:"form-control", :style => "width:200px"} %>
</div>
<div class="field">
  <%= f.label :app_date, 'Application Date' %><br>
  <%= f.date_select :app_date %>
</div>

<div class="field">
  <%=f.label :products%><br>
  <%=f.collection_check_boxes :product_ids,Product.all,:id, :name, {},{class: "checkbox"}%>
</div>


<div class="field">
  <%= f.label :app_type, 'Application Type' %><br>
  <%= f.select :app_type, options_for_select([["Foliar", 'foliar'],["Soil",'soil'],["Drip",'drip'],["Flood",'flood']]),{include_blank: ''},{class:"form-control", :style => "width:80px"} %>
</div>

<div class="field">
  <%= f.label :competitor, 'Competitors product' %><br>
  <%= f.text_field :competitor,{class:"form-control",:style => "width:200px"} %>
</div>

<div class="field">
  <%= f.label :follow_date, 'Follow up Date' %><br>
  <%= f.date_select :follow_date,{class:"form-control",:style => "width:200px"} %>
</div>

<%=link_to_remove_association 'Remove Product Application', f %>
  </div>

app/views/pre_demonstrations/_form.html.erb
<%= form_for(@pre_demonstration) do |f| %>
  <% if @pre_demonstration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pre_demonstration.errors.count, "error") %> prohibited this pre_demonstration from being saved:</h2>

      <ul>
      <% @pre_demonstration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="container">
      <div class="panel panel-primary">
        <div class="panel-heading text-center">
          <h1 class="panel-title text-center">
            <%= link_to 'Back', fa_activities_path, class: "btn btn-success pull-left",:style=>'color:#FFFFFF' %>
            <%= link_to 'Cancel', root_path, class: "btn btn-danger pull-right",:style=>'color:#FFFFFF' %>
            <b>New Pre-Demonstration</b>
          </h1>
        </div>

    <div class="panel-body">
      <div class="row">
        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <b>Farmer Information</b>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label>
                      Farmer
                    </label>
                    <%= f.number_field :farmer_id,{class:"form-control"} %>
                  </div>
                </div>
                <div class="row"></div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>
                      Crop
                    </label>
                    <%=f.number_field :crop_id,{class:"form-control"}%>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label>
                      FA Activity
                    </label>
                    <%=f.number_field :fa_activity_id,{class:"form-control"}%>
                  </div>
                </div>
              </div>



              <div class="row">
                <div class="col-md-8">
                  <div class="form-group">
                    <label>
                      Crop Growth
                    </label>
                    <%= f.select :crop_growth, options_for_select([["Soil Preparation",'soil_prep'],["30 - 40 days after sowing / transplanting", '30_40_days_after_sowing_transplant'],
                                                                   ["40 - 60 days after sowing / transplanting",'40_60_days_after_sowing_transplant'],
                                                                   ["100 - 120 Days after sowing / transplanting",'100_120_days_after_sowing_transplant'],
                                                                   ["120 days after sowing / transplanting",'120_days_after_sowing_transplant'],["30 - 40 days before flowering",'30_40_days_before_flowering'],
                                                                   ["Before flowering",'before_flowering'],["After flowering",'after_flowering'],["At fruit setting",'fruit_setting'],["After fruit setting",
                                                                                                                                                                                       'after_fruit_setting'],["30 - 40 days after pruning", '30_40_days_after_pruning'], ["50 - 60 days after pruning",'50_60_days_after_pruning'],
                                                                   ["During vegetative stage",'during_vegetative_stage'],["Immediately after pruning",'immediately_after_pruning'],["20 - 30 days after breaking dormancy",
                                                                                                                                                                                    '20_30_days_after_breaking_dormancy'],["After bunch formation",'after_bunch_formation'],["After Flowering - Before Fruit / Grain Setting", 'after_flower_before_fruit_grain_setting'],
                                                                   ["At Fruit / Grain Setting", 'at_fruit_grain_setting'],["After Fruit / Grain Setting",'after_fruit_grain_setting'],[" Boll / Bulb / Pod Formation",'boll_pod_formation'],
                                                                   ["After Plucking",'after_plucking'],["After 2-3 plucking",'2-3_after_plucking']]), {include_blank: ''}, {class: 'form-control', :style => "290px"} %>
                  </div>
                  </div>
                </div>


              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label>
                      Crop Condition
                    </label>
                    <%= f.select :condition, options_for_select([["Drought", 'drought'],["Flower/Fruit Shedding", 'flower'], ["Healty Growth", 'healthy_growth'], ["Heat Stress",'heat_stress'],
                                                                 ["Infestation - Bacterial", 'bacterial_infest'], ["Infestation - Fungal",'fungal_infest'], ["Infestation - Mite", 'mite_infest'],
                                                                 ["Infestation - Nematode", 'nematode_infest'],["Infestation - Suck Pest",'suck_pest_infest'], ["Infestation - Viral",'viral_infest'],
                                                                 ["Infestation - Other",'other_infest'], ["Leaf Curling", 'leaf_curling'], ["Root Rot",'root_rot'],["Root Wilt", 'root_wilt'],
                                                                 ["Salt Stress", 'salt_stress'], ["Water Stress",'water_stress']]), {include_blank: ''}, {class: 'form-control'} %>
                  </div>
                </div>
              </div>
          </div>
        </div>
    </div>




    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading text-center">
                <b>Application Information</b>
          <div class="panel-body">
            <div class="row">
              <div class="col-md-6">
                <div class="field">
            <%=f.fields_for :applications do |app|%>
                <%=render 'application_fields', f: app%>
            <%end%>
          </div>
          </div>
            </div>
            </div>




  </div>
  <div class="field">

  </div>
  <div class="field">
    <%= f.label :demo_code %><br>
    <%= f.text_field :demo_code,{class:"form-control", :style => "width:200px"} %>
  </div>
    <div>
      <%=f.fields_for :applications do |app|%>
          <%=render 'application_fields', f: app%>
      <%end%>
      <div class="links">
        <%=link_to_add_association 'More Product Application?', f, :applications%>
      </div>
    </div>


        <div class="col-md-6">
          <div class="actions">
            <%= f.submit "Submit", class: "btn btn-primary pull-right"%>
          </div>
          </div>

        </div>
      </div>
    </div>
    </div>
    </div>
    </div>






<% end %>

app/views/pre_demonstrations/edit.html.erb
<h1>Editing Pre Demonstration</h1>

<%= render 'form' %>

<%= link_to 'Show', @pre_demonstration %> |
<%= link_to 'Back', pre_demonstrations_path %>

app/views/pre_demonstrations/index.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading ">
      <h1 class="panel-title ">
        <b> Pre-Demonstrations</b>
      </h1>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-12">
          <table class="table table-bordered">
            <tbody>
            <tr>
              <th class="text-center">
                Farmer
              </th>
              <th class="text-center">
                Crop
              </th>
              <th class="text-center">
                Crop Condition
              </th>
              <th class="text-center">
                Crop Growth
              </th>

              <th class="text-center">
                Demonstration Code
              </th>
              <td class="text-center">

              </td>
            </tr>
            <tr>
              <% @pre_demonstrations.each do |pre_demo| %>
                  <td class="text-center">
                    <%= pre_demo.farmer_id %>
                  </td>
                  <td class="text-center">
                    <%= pre_demo.crop.crop %>
                  </td>
                  <td class="text-center">
                    <%= pre_demo.condition %>
                  </td>
                  <td class="text-center">
                    <%= pre_demo.crop_growth %>
                  </td>
                  <td class="text-center">
                    <%= pre_demo.demo_code %>
                  </td>
                  <td class="text-center">
                    <%= link_to 'New Demonstration', new_demonstration_path(:pre_id => pre_demo.id), class: 'btn btn-primary',:style=>'color:#FFFFFF',  id: 'hope'%>
                  </td>
                  <td><td><%= link_to 'Delete', pre_demo, method: :delete, data: { confirm: 'Are you sure?' } %></td></td>
                  </tr>
              <% end %>
              </tbody>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pre_demonstrations/new.html.erb
  <%= render 'form' %>
  <%= link_to 'Back', pre_demonstrations_path %>
</div>
</div>

app/views/pre_demonstrations/show.html.erb
<p>
  <strong>Farmer:</strong>
  <%= @pre_demonstration.farmer_id %>
</p>

<p>
  <strong>Crop:</strong>
  <%= @pre_demonstration.crop_id %>
</p>

<p>
  <strong>Fa activity:</strong>
  <%= @pre_demonstration.fa_activity_id %>
</p>

<p>
  <strong>Crop growth:</strong>
  <%= @pre_demonstration.crop_growth %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @pre_demonstration.condition %>
</p>

<p>
  <strong>Demo code:</strong>
  <%= @pre_demonstration.demo_code %>
</p>

<%= link_to 'Edit', edit_pre_demonstration_path(@pre_demonstration) %> |
<%= link_to 'Back', pre_demonstrations_path %>