config/routes.rb
Rails.application.routes.draw do
  resources :dealeravatars
  resources :dealerphotos
  resources :singles
  resources :boxes
  resources :demonstration_attachments
  resources :meet_sr_farmers
  resources :meet_fas
  resources :meet_dealers
  resources :meet_state_managers
  resources :business_developments
  resources :sr_activities
  resources :post_demonstrations
  get 'demo_date/populate_dates'

  resources :demonstrations
  resources :farmers
  resources :dealer_blanks
  resources :blank_checks
  resources :dealer_securities
  resources :security_checks
  resources :dealer_props
  resources :proprietors
  resources :positions
  resources :fa_targets
  resources :targets
  resources :field_assistants
  resources :pocket_crops
  resources :pocket_districts
  resources :pocket_dats
  resources :pocket_infos
  resources :villages
  resources :talukas
  resources :crops
  resources :districts
  resources :pockets
  resources :products
  resources :applications
  resources :pre_demonstrations
  resources :assist_reps
  resources :dealer_visits
  resources :product_prescriptions
  resources :meet_farmers
  resources :fa_activities
  resources :banks
  resources :dealers
  resources :demos
  resources :pockets
  resources :demoresults
  resources :prodsamples
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'home#index'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated
    end
  end
  resources :users
  resources :states

  resources :home

end

app/models/post_demonstration.rb
class PostDemonstration < ActiveRecord::Base
  belongs_to :demonstration
  belongs_to :fa_activity
  has_many :demonstration_attachments
  mount_uploader :demo_photo, AvatarUploader
  accepts_nested_attributes_for :demonstration_attachments, allow_destroy: true, reject_if: :all_blank

  def set_bool
    self[:contacrsr] ? 'Yes' : 'No'
  end
end

app/controllers/post_demonstrations_controller.rb
class PostDemonstrationsController < ApplicationController
  before_action :set_post_demonstration, only: [:show, :edit, :update, :destroy]

  # GET /post_demonstrations
  # GET /post_demonstrations.json
  def index
    @post_demonstrations = PostDemonstration.all
  end

  # GET /post_demonstrations/1
  # GET /post_demonstrations/1.json
  def show
  end

  # GET /post_demonstrations/new
  def new
    @post_demonstration = PostDemonstration.new
  end

  # GET /post_demonstrations/1/edit
  def edit
  end

  # POST /post_demonstrations
  # POST /post_demonstrations.json
  def create
    @post_demonstration = PostDemonstration.new(post_demonstration_params)

    respond_to do |format|
      if @post_demonstration.save
        format.html { redirect_to @post_demonstration, notice: 'Post demonstration was successfully created.' }
        format.json { render :show, status: :created, location: @post_demonstration }
      else
        format.html { render :new }
        format.json { render json: @post_demonstration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_demonstrations/1
  # PATCH/PUT /post_demonstrations/1.json
  def update
    respond_to do |format|
      if @post_demonstration.update(post_demonstration_params)
        format.html { redirect_to @post_demonstration, notice: 'Post demonstration was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_demonstration }
      else
        format.html { render :edit }
        format.json { render json: @post_demonstration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_demonstrations/1
  # DELETE /post_demonstrations/1.json
  def destroy
    @post_demonstration.destroy
    respond_to do |format|
      format.html { redirect_to post_demonstrations_url, notice: 'Post demonstration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_demonstration
      @post_demonstration = PostDemonstration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_demonstration_params
      params.require(:post_demonstration).permit(:demonstration_id, :observation, :contacrsr, :comment, :demo_photo,:fa_activity_id)
    end
end

app/helpers/post_demonstrations_helper.rb
module PostDemonstrationsHelper
end

app/views/post_demonstrations/_form.html.erb
<%= form_for(@post_demonstration) do |f| %>
  <% if @post_demonstration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_demonstration.errors.count, "error") %> prohibited this post_demonstration from being saved:</h2>

      <ul>
      <% @post_demonstration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :demonstration_id %><br>
    <%= f.collection_select :demonstration_id, Demonstration.all, :id,:demo_code %>
  </div>
  <div class="field">
    <%= f.label :observation %><br>
    <%= f.select :observation, options_for_select([["Expected Results",'expected'], ["Unexpected Results",'unexpected']]),
                 {include_blank: ''}%>
  </div>

  <div class="field", id="unexpected_comments">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field", id="demo_pictures">
    <%= f.label :demo_photo %><br>
    <%= f.file_field :demo_photo %>
  </div>
    <div class="field">
      <%= f.label :contacrsr, 'Contact Sales Representative' %><br>
      <%= f.check_box :contacrsr %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_demonstrations/edit.html.erb
<h1>Editing Post Demonstration</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_demonstration %> |
<%= link_to 'Back', post_demonstrations_path %>

app/views/post_demonstrations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Post Demonstrations</h1>

<table>
  <thead>
    <tr>
      <th>Demonstration</th>
      <th>Observation</th>
      <th>Contacrsr</th>
      <th>Comment</th>
      <th>Demo photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_demonstrations.each do |post_demonstration| %>
      <tr>
        <td><%= post_demonstration.demonstration_id %></td>
        <td><%= post_demonstration.observation %></td>
        <td><%= post_demonstration.contacrsr %></td>
        <td><%= post_demonstration.comment %></td>
        <td><%= post_demonstration.demo_photo %></td>
        <td><%= link_to 'Show', post_demonstration %></td>
        <td><%= link_to 'Edit', edit_post_demonstration_path(post_demonstration) %></td>
        <td><%= link_to 'Destroy', post_demonstration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post demonstration', new_post_demonstration_path %>

app/views/post_demonstrations/new.html.erb
<h1>New Post Demonstration</h1>

<%= render 'form' %>

<%= link_to 'Back', post_demonstrations_path %>

app/views/post_demonstrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Demonstration:</strong>
  <%= @post_demonstration.demonstration_id %>
</p>

<p>
  <strong>Observation:</strong>
  <%= @post_demonstration.observation %>
</p>

<p>
  <strong>Contacrsr:</strong>
  <%= @post_demonstration.contacrsr %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @post_demonstration.comment %>
</p>

<p>
  <strong>Demo photo:</strong>
  <%= image_tag @post_demonstration.demo_photo_url(:thumb).to_s%>
</p>

<%= link_to 'Edit', edit_post_demonstration_path(@post_demonstration) %> |
<%= link_to 'Back', post_demonstrations_path %>